const {test}=require('node:test');
const assert=require('node:assert/strict'), fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {Collection,PermissionsBitField,ChannelType}=require('discord.js');
function setup(){
 const files=new Map(),cache=new Map(),forms=[],confirms=[],sent=[];const root=path.join(__dirname,'..');
 const fakeFs={existsSync:f=>files.has(f),readFileSync:f=>files.get(f),mkdirSync(){},writeFileSync:(f,v)=>files.set(f,v),renameSync:(a,b)=>{files.set(b,files.get(a));files.delete(a);}};
 const guild={id:'guild',ownerId:'admin',name:'Test',memberCount:3};
 const channel={id:'channel',type:ChannelType.GuildText,isTextBased:()=>true,permissionsFor:()=>({has:()=>true}),send:async p=>{sent.push(p);return{id:'msg'};},setRateLimitPerUser:async n=>{channel.slowmode=n;}};
 guild.channels={fetch:async id=>id?channel:new Collection([['channel',channel]])};guild.roles={fetch:async()=>new Collection()};guild.members={fetch:async()=>new Collection()};
 const message={guild,channel,author:{id:'admin'},member:{permissions:{has:()=>true},roles:{cache:new Collection()}},reply:async p=>{sent.push(p);return{delete:async()=>{}};}};
 const g={config:{suggestionChannelId:'original'},id:v=>v,embed:(t,d)=>({title:t,description:d}),reply:async(m,e)=>sent.push(e),list:async(m,t,l)=>sent.push(l),date:String,role:async()=>null,member:async()=>null};
 function load(relative){const file=path.resolve(root,relative);if(cache.has(file))return cache.get(file);const module={exports:{}};vm.runInNewContext(fs.readFileSync(file,'utf8'),{module,__dirname:path.dirname(file),Buffer,URL,AbortSignal,Date,setTimeout,clearTimeout,setInterval,clearInterval,console,require:name=>{if(name==='node:fs')return fakeFs;if(name.endsWith('config.json'))return{owners:['admin'],defaultPrefix:'+'};if(name==='./general')return g;if(name==='./ownerUI')return{form:async(m,t,f,a)=>forms.push({fields:f,action:a}),confirm:async(m,t,a)=>confirms.push(a)};if(name.startsWith('.'))return load(path.resolve(path.dirname(file),name+'.js'));return require(name);}},{filename:file});cache.set(file,module.exports);return module.exports;}
 return{load,forms,confirms,sent,message,guild,channel,store:load('utils/serverConfigStore.js'),commands:load('utils/serverConfigCommands.js'),runtime:load('utils/serverConfigRuntime.js'),client:{commands:new Collection(),ownerCommands:new Collection(),guilds:{cache:new Collection([['guild',guild]])}}};
}
test('configuration séparée par serveur et commandes administratives protégées',async()=>{const s=setup();s.store.mutate('guild',v=>{v.autopublish=true;});assert.equal(s.store.get('other').autopublish,false);s.message.author.id='visitor';s.message.member.permissions.has=()=>false;await assert.rejects(s.commands('autopublish').execute(s.message,['off'],s.client),/administrateurs/);assert.equal(s.store.get('guild').autopublish,true);});
test('slowmode respecte les 6h et autodelete garde les cibles séparées',async()=>{const s=setup();await s.commands('slowmode').execute(s.message,['6h'],s.client);assert.equal(s.channel.slowmode,21600);await assert.rejects(s.commands('slowmode').execute(s.message,['7h'],s.client),/Maximum/);await s.commands('autodelete').execute(s.message,['snipe','reply','10s'],s.client);assert.equal(s.store.get('guild').autodelete.snipe.reply,10000);assert.equal(s.store.get('guild').autodelete.snipe.commande,undefined);});
test('reminder persistant envoyé une fois et date sans fuseau refusée',async()=>{const s=setup();await s.commands('reminder').execute(s.message,[],s.client);await assert.rejects(s.forms[0].action({text:'test',date:'2099-01-01T12:00:00',channel:''}),/fuseau/);await s.forms[0].action({text:'test',date:'1h',channel:''});s.store.mutate('guild',v=>{v.reminders['1'].at=Date.now()-1;});await s.runtime.tick(s.client);await s.runtime.tick(s.client);assert.equal(s.sent.filter(p=>p.content==='test').length,1);assert.equal(s.store.get('guild').reminders['1'].sent,true);});
test('suggestion settings sauvegarde le salon et clear attend une confirmation',async()=>{const s=setup();await s.commands('suggestion').execute(s.message,['settings'],s.client);assert.equal(s.forms[0].fields[1].value,'original');await s.forms[0].action({enabled:'off',channel:'channel'});assert.equal(s.store.get('guild').suggestions.enabled,false);s.store.mutate('guild',v=>{v.customCommands.hello={text:'hi'};});await s.commands('clear').execute(s.message,['customs'],s.client);assert.ok(s.store.get('guild').customCommands.hello);await s.confirms[0]();assert.equal(Object.keys(s.store.get('guild').customCommands).length,0);});
test('tickets refusent les utilisateurs externes et menus refusent les rôles dangereux',async()=>{const s=setup(),i=s.load('utils/serverConfigInteractions.js');assert.equal(i.ticketAccess(s.guild,'visitor',{permissions:{has:()=>false},roles:{cache:new Collection()}},{ownerId:'other'}),false);assert.equal(i.ticketAccess(s.guild,'creator',{permissions:{has:()=>false},roles:{cache:new Collection()}},{ownerId:'creator'}),true);assert.equal(Boolean(i.safeRole({id:'role',managed:false,editable:true,permissions:new PermissionsBitField(8n)},s.guild)),false);});
test('les noms partagés choisissent la variante de configuration',()=>{const s=setup();for(const [name,args]of [['set',['perm']],['leave',['settings']],['suggestion',['settings']],['clear',['customs']]]){assert.equal(s.commands(name).matches(args),true);assert.equal(s.commands(name).matches(['other']),false);}});
test('les permissions locales accordées à un membre restent limitées au serveur',()=>{const s=setup();s.store.mutate('guild',v=>{v.grants['command:ping']={roles:[],users:['admin']};});assert.equal(s.store.granted(s.message,'ping','Administrator'),true);assert.equal(s.store.granted({...s.message,guild:{id:'other'}},'ping','Administrator'),false);assert.equal(s.store.granted(s.message,'different','Administrator'),false);});
test('la création custom en mode owner refuse un administrateur sans grade owner',async()=>{const s=setup();await assert.rejects(s.commands('custom',{ownerOnly:true}).execute({...s.message,author:{id:'visitor'}},['test'],s.client),/owners/);assert.equal(s.forms.length,0);});
