const { ChannelType, PermissionFlagsBits:P }=require('discord.js');
const g=require('./general'),tools=require('./managementTools'),logs=require('./logs'),ui=require('./ownerUI');
const definitions={settings:[['settings','Affiche les paramètres du bot sur le serveur']],set:[['set modlogs','Choisit les actions affichées dans les logs de modération'],['set boostembed','Personnalise l’embed de boost']],autoconfiglog:[['autoconfiglog','Crée et configure un salon privé pour chaque type de logs']],boostembed:[['boostembed <on/off>','Active ou désactive les embeds de boost'],['boostembed test','Teste l’embed de boost']],nolog:[['nolog <add/del> [salon]','Exclut ou réactive les logs des messages et du vocal dans des salons']],raidlog:[['raidlog [salon]','Active les logs antiraid'],['raidlog off','Désactive les logs antiraid']],join:[['join settings','Configure les actions à l’arrivée des membres']],leave:[['leave settings','Configure les actions au départ des membres']],modmail:[['modmail','Configure les modmails sur un seul serveur']]};
for(const [name,label]of [['modlog','modération'],['messagelog','messages supprimés et modifiés'],['voicelog','activité vocale'],['boostlog','boosts'],['rolelog','rôles']])definitions[name]=[[`${name} on [salon]`,`Active les logs de ${label}`],[`${name} off`,`Désactive les logs de ${label}`]];
const types={modlog:'mod',messagelog:'message',voicelog:'voice',boostlog:'boost',rolelog:'role'};
async function target(message,query){const c=await tools.channel(message,query);if(!c.isTextBased()||!c.permissionsFor(message.guild.members.me)?.has([P.ViewChannel,P.SendMessages,P.EmbedLinks]))throw new Error('Salon textuel et permissions ViewChannel, SendMessages, EmbedLinks requis.');return c;}
async function execute(name,message,args,client){
 tools.guard(message);const guild=message.guild,send=text=>g.reply(message,g.embed('Logs',text)),form=(title,fields,action)=>ui.form(message,title,fields,action,tools.authorize(message));
 if(['join','leave','modmail'].includes(name))return require('./serverConfigCommands')(name).execute(message,args,client);
 if(types[name]){if(!['on','off'].includes(args[0]))throw new Error(`Utilise ${name} on [salon] ou ${name} off.`);const c=args[0]==='on'?await target(message,args.slice(1).join(' ')):null;logs.mutate(guild.id,s=>{s.channels[types[name]]=c?.id||null;});return send(c?`Logs activés dans <#${c.id}>.`:'Logs désactivés.');}
 if(name==='raidlog'){const next=args[0]==='off'?['off']:args[0]==='on'?args:['on',...args];return require('./antiraidCommands')('raidlog').execute(message,next,client);}
 if(name==='settings'){
  const config=require('./serverConfigStore').get(guild.id),management=require('./managementStore').get(guild.id),raid=require('./antiraidStore').get(guild.id),state=logs.get(guild.id);
  const lines=Object.entries(types).map(([command,type])=>`**${command} :** ${state.channels[type]?`<#${state.channels[type]}>`:'désactivé'}`);
  lines.push(`**raidlog :** ${raid.logEnabled?`<#${raid.logChannelId}>`:'désactivé'}`,`**Salons exclus :** ${state.excluded.map(id=>`<#${id}>`).join(', ')||'aucun'}`,`**Embed boost :** ${state.boostEmbed.enabled?'on':'off'}`,`**Bienvenue / départ :** ${config.joins.enabled?'on':'off'} / ${config.leaves.enabled?'on':'off'}`,`**Tickets / vocaux temporaires :** ${config.tickets.enabled?'on':'off'} / ${config.tempVoice.enabled?'on':'off'}`,`**Suggestions :** ${config.suggestions.enabled?'on':'off'} — <#${config.suggestions.channelId||g.config.suggestionChannelId||message.channel.id}>`,`**Publication automatique :** ${config.autopublish?'on':'off'}`,`**Commandes custom :** ${Object.keys(config.customCommands).length}`,`**Reminders :** ${Object.keys(config.reminders).length}`,`**Autoreacts :** ${Object.keys(management.autoReacts).length}`,`**Antiraid :** ${Object.entries(raid.modes).map(([k,v])=>`${k}: ${v}`).join(', ')}`);
  const moderation=require('./moderationStore').get(guild.id);
  lines.push(`**Mute :** ${moderation.timeout?'Timeout Discord':`rôle ${moderation.muteRoleId?`<@&${moderation.muteRoleId}>`:'non configuré'}`}`,`**Limite clear :** ${moderation.clearLimit}`,`**Antispam :** ${moderation.antispam?'on':'off'} — ${moderation.spamLimit.count}/${moderation.spamLimit.duration/1000}s`,`**Antilink :** ${moderation.antilink?'on':'off'} — ${moderation.linkMode}`,`**Mentions :** ${moderation.antimassmention?'on':'off'} — seuil ${moderation.mentionLimit}`,`**Mots interdits :** ${moderation.badwordsEnabled?'on':'off'} — ${moderation.words.length} mot(s)`,`**Ancienneté :** ${moderation.ancientAge/86400000} jour(s)`,`**Sanctions :** ${moderation.punishments.length}`,`**Commandes publiques :** ${moderation.publicEnabled?'on':'off'}`,`**Salons photo :** ${moderation.picChannels.map(id=>`<#${id}>`).join(', ')||'aucun'}`);
  return g.list(message,'Paramètres du serveur',lines);
 }
 if(name==='nolog'){if(!['add','del'].includes(args[0]))throw new Error('Utilise nolog add/del [salon].');const channels=[];for(const query of (args.slice(1).join(' ')||message.channel.id).split(',,').map(x=>x.trim()).filter(Boolean))channels.push((await tools.channel(message,query)).id);logs.mutate(guild.id,s=>{s.excluded=args[0]==='add'?[...new Set([...s.excluded,...channels])]:s.excluded.filter(id=>!channels.includes(id));});return send('Exclusions mises à jour.');}
 if(name==='boostembed'){if(args[0]==='test'){await logs.boostEmbed(message.member,true);return send('Embed de test envoyé.');}if(!['on','off'].includes(args[0]))throw new Error('Utilise boostembed on/off/test.');logs.mutate(guild.id,s=>{s.boostEmbed.enabled=args[0]==='on';});return send('Embed de boost mis à jour.');}
 if(name==='set'&&args[0]==='modlogs'){const config=logs.get(guild.id);return form('Logs de modération',Object.entries({bans:'Bans et débannissements',kicks:'Expulsions',timeouts:'Timeouts',messages:'Suppressions de messages'}).map(([id,label])=>({id,label:`${label} : on/off`,value:config.moderation[id]?'on':'off',required:true})),async v=>{if(Object.values(v).some(x=>!['on','off'].includes(x)))throw new Error('Valeurs attendues : on ou off.');logs.mutate(guild.id,s=>{s.moderation=Object.fromEntries(Object.entries(v).map(([k,x])=>[k,x==='on']));});});}
 if(name==='set'&&args[0]==='boostembed'){const config=logs.get(guild.id).boostEmbed;return form('Embed de boost',[{id:'title',label:'Titre',value:config.title,required:true,max:256},{id:'description',label:'Texte : {member}, {server}, {count}',value:config.description,required:true,paragraph:true,max:3500},{id:'channel',label:'Salon (vide = salon boostlog)',value:config.channelId||''}],async v=>{const c=v.channel?await target(message,v.channel):null;logs.mutate(guild.id,s=>{Object.assign(s.boostEmbed,{title:v.title,description:v.description,channelId:c?.id||null});});});}
 if(name==='autoconfiglog')return ui.confirm(message,'Créer les salons privés de logs ? Les réglages existants seront conservés.',async()=>{
  const config=logs.get(guild.id),raid=require('./antiraidStore').get(guild.id),names={mod:'logs-moderation',message:'logs-messages',voice:'logs-vocaux',boost:'logs-boosts',role:'logs-roles',raid:'logs-antiraid'};
  for(const [type,label]of Object.entries(names)){const id=type==='raid'?raid.logChannelId:config.channels[type];if(id&&await guild.channels.fetch(id).catch(()=>null))continue;
   const channel=await guild.channels.create({name:label,type:ChannelType.GuildText,permissionOverwrites:[{id:guild.id,deny:[P.ViewChannel]},{id:client.user.id,allow:[P.ViewChannel,P.SendMessages,P.EmbedLinks]},{id:message.author.id,allow:[P.ViewChannel,P.ReadMessageHistory]}],reason:'Configuration automatique des logs'});
   if(type==='raid')require('./antiraidStore').save(guild.id,{logEnabled:true,logChannelId:channel.id});else logs.mutate(guild.id,s=>{s.channels[type]=channel.id;});
  }
 },tools.authorize(message));
 throw new Error('Sous-commande invalide.');
}
module.exports=name=>({name,category:'Logs',lockedPermission:true,defaultPermission:'Administrator',usage:definitions[name][0][0],description:definitions[name][0][1],helpEntries:definitions[name].map(([usage,description])=>({usage,description})),...(['set','join','leave','raidlog','modmail'].includes(name)?{matches:a=>name==='set'?['modlogs','boostembed'].includes(a[0]):['join','leave'].includes(name)?a[0]==='settings':true}:{}),execute:(m,a,c)=>execute(name,m,a,c)});
module.exports.names=Object.keys(definitions);
