const {ChannelType,PermissionFlagsBits:P}=require('discord.js');
const g=require('./general'),tools=require('./managementTools'),settings=require('./settings'),store=require('./moderationActionsStore'),engine=require('./moderationActions'),ui=require('./ownerUI');
const {duration}=require('./antiraidStore');
const definitions={sanctions:'sanctions <membre>',del:'del sanction <membre> <nombre>',clear:'clear [nombre] [membre]',warn:'warn <membre> [raison]',mute:'mute <membre> [raison]',tempmute:'tempmute <membre> <durée> [raison]',unmute:'unmute <membre>',cmute:'cmute <membre> [raison]',tempcmute:'tempcmute <membre> <durée> [raison]',uncmute:'uncmute <membre>',mutelist:'mutelist',unmuteall:'unmuteall',kick:'kick <membre> [raison]',ban:'ban <membre> [raison]',tempban:'tempban <membre> <durée> [raison]',unban:'unban <membre>',banlist:'banlist',lock:'lock [salon]',unlock:'unlock [salon]',lockall:'lockall',unlockall:'unlockall',hide:'hide [salon]',unhide:'unhide [salon]',hideall:'hideall',unhideall:'unhideall',addrole:'addrole <membre> <rôle>',delrole:'delrole <membre> <rôle>',derank:'derank <membre>'};
const descriptions={sanctions:'Affiche les sanctions reçues par un membre',del:'Supprime une sanction de l’historique',clear:'Supprime des messages, avec filtre de membre facultatif',warn:'Avertit un ou plusieurs membres',mute:'Mute un ou plusieurs membres',tempmute:'Mute temporairement un ou plusieurs membres',unmute:'Met fin aux mutes',cmute:'Mute des membres dans le salon actuel',tempcmute:'Mute temporairement dans le salon actuel',uncmute:'Rétablit les permissions des membres dans le salon',mutelist:'Liste les mutes en cours',unmuteall:'Retire tous les mutes après confirmation',kick:'Expulse des membres',ban:'Bannit des membres',tempban:'Bannit temporairement des membres',unban:'Retire des bannissements',banlist:'Liste les bannissements',lock:'Ferme un salon',unlock:'Rétablit les permissions d’un salon',lockall:'Ferme tous les salons après confirmation',unlockall:'Rétablit les permissions de tous les salons',hide:'Cache un salon',unhide:'Rétablit la visibilité d’un salon',hideall:'Cache tous les salons après confirmation',unhideall:'Rétablit la visibilité de tous les salons',addrole:'Ajoute des rôles à des membres',delrole:'Retire des rôles à des membres',derank:'Retire les rôles sauf les rôles protégés'};
// Mentions et IDs peuvent être groupés ; pour les noms composés utilise des groupes séparés par ,,.
function input(args,timed=false){const text=args.join(' '),tokens=text.includes(',,')?text.split(',,').map(x=>x.trim()).filter(Boolean):args;let index=0,queries=[];
 if(text.includes(',,')){for(;index<tokens.length;index++){if(timed&&/^\d+(?:\.\d+)?(?:ms|s|m|h|d|j)$/i.test(tokens[index]))break;if(!timed&&index===tokens.length-1&&tokens.length>1)break;queries.push(...tools.parts([tokens[index]]));}if(!queries.length)queries.push(tokens[index++]);}
 else{while(index<tokens.length&&/^(?:<@!?\d+>|\d{15,22})$/.test(tokens[index]))queries.push(tokens[index++]);if(!queries.length)queries.push(tokens[index++]);}
 const time=timed?duration(tokens[index++]):0;if(timed&&time<1000)throw new Error('Durée minimale : 1s.');return{queries,reason:tokens.slice(index).join(text.includes(',,')?' ,, ':' ')||'Aucune raison',time};}
async function members(message,queries){const result=[];for(const query of queries){const m=await g.member(message,[query]);if(!m)throw new Error(`Membre introuvable ou nom ambigu : ${query}`);if(!result.some(v=>v.id===m.id))result.push(m);}return result;}
async function userIds(message,args,client){const result=[];for(const query of tools.parts(args)){const id=g.id(query);if(/^\d{15,22}$/.test(id)){result.push(id);continue;}const m=await g.member(message,[query]);if(m){result.push(m.id);continue;}const bans=await message.guild.bans.fetch(),matches=bans.filter(b=>[b.user.tag,b.user.username].includes(query));if(matches.size!==1)throw new Error(`Utilisateur introuvable ou ambigu : ${query}`);result.push(matches.first().user.id);}return[...new Set(result)];}
async function execute(name,message,args,client){
 tools.guard(message);const guild=message.guild,send=text=>g.reply(message,g.embed('Modération',text)),confirm=(text,fn)=>ui.confirm(message,text,fn,tools.authorize(message));
 if(name==='sanctions'){const [id]=await userIds(message,args,client);if(!id)throw new Error('Membre requis.');return g.list(message,'Sanctions', (store.get(guild.id).sanctions[id]||[]).map((s,i)=>`**${i+1}. ${s.action}** — ${g.date(s.at)}\nResponsable : <@${s.actorId}> — ${s.reason}${s.duration?' — '+s.duration/1000+'s':''}`));}
 if(name==='del'){if(args[0]!=='sanction')throw new Error('Utilise del sanction membre nombre.');const number=Number(args.at(-1));if(!Number.isInteger(number)||number<1)throw new Error('Numéro de sanction invalide.');const [id]=await userIds(message,args.slice(1,-1),client),entry=(store.get(guild.id).sanctions[id]||[])[number-1];if(!id||!entry)throw new Error('Sanction introuvable.');return confirm('Supprimer cette entrée de l’historique ?',()=>store.mutate(guild.id,s=>{const index=(s.sanctions[id]||[]).findIndex(v=>v.id===entry.id);if(index<0)throw new Error('Sanction déjà supprimée.');s.sanctions[id].splice(index,1);}));}
 if(name==='clear'){
  if(args[0]==='sanctions'||args[0]==='all'&&args[1]==='sanctions'){const all=args[0]==='all',ids=all?[]:await userIds(message,args.slice(1),client);return confirm('Effacer cet historique de sanctions ? Les sanctions actives resteront en place.',()=>store.mutate(guild.id,s=>{if(all)s.sanctions={};else for(const id of ids)delete s.sanctions[id];}));}
  const count=args[0]?Number(args[0]):require('./moderationStore').get(guild.id).clearLimit,limit=require('./moderationStore').get(guild.id).clearLimit;if(!Number.isInteger(count)||count<1||count>limit)throw new Error(`Nombre de 1 à ${limit} attendu.`);
  const target=args.length>1?(await members(message,[args.slice(1).join(' ')]))[0]:null;if(!message.channel.bulkDelete)throw new Error('Salon incompatible.');let before=message.id,remaining=count,deleted=0,scanned=0;
  while(remaining>0&&scanned<10000){const batch=await message.channel.messages.fetch({limit:target?100:Math.min(100,remaining),before});if(!batch.size)break;scanned+=batch.size;before=batch.last().id;const eligible=batch.filter(m=>(!target||m.author.id===target.id)&&!m.pinned&&Date.now()-m.createdTimestamp<14*86400000-5000);const selected=new (require('discord.js').Collection)([...eligible].slice(0,remaining));if(selected.size){deleted+=(await message.channel.bulkDelete(selected,true)).size;remaining-=selected.size;}if(!target)remaining=Math.max(0,count-scanned);if(batch.size<100||Date.now()-batch.last().createdTimestamp>=14*86400000)break;}
  return send(`${deleted} message(s) supprimé(s). Les messages épinglés ou de plus de 14 jours sont conservés.`);
 }
 if(name==='banlist'){const bans=await guild.bans.fetch();return g.list(message,'Bannissements',bans.map(b=>`${b.user.tag} (${b.user.id}) — ${b.reason||'Aucune raison'}`));}
 if(['lock','unlock','hide','unhide','lockall','unlockall','hideall','unhideall'].includes(name)){
  const all=name.endsWith('all'),base=name.replace(/all$/,''),kind=base.includes('hide')?'hide':'lock',enable=['lock','hide'].includes(base);
  const perform=async()=>{const channels=all?[...(await guild.channels.fetch()).values()].filter(c=>c&&[ChannelType.GuildText,ChannelType.GuildVoice,ChannelType.GuildAnnouncement,ChannelType.GuildStageVoice,ChannelType.GuildForum,ChannelType.GuildMedia].includes(c.type)):[await tools.channel(message,args.join(' '))],results=[];for(const c of channels){try{if(!c.permissionOverwrites)throw new Error('Salon incompatible');await engine.channelPermissions(c,kind,enable,client.user.id);results.push(`<#${c.id}> : effectué`);}catch(e){results.push(`<#${c.id}> : ${e.message}`);}}await g.list(message,'Permissions des salons',results);};
  return all?confirm('Modifier les permissions de tous les salons ?',perform):perform();
 }
 if(name==='mutelist'||name==='unmuteall'){
  const config=require('./moderationStore').get(guild.id),state=store.get(guild.id),all=await guild.members.fetch(),muted=all.filter(m=>m.communicationDisabledUntilTimestamp>Date.now()||(config.muteRoleId&&m.roles.cache.has(config.muteRoleId))||(state.mutes[m.id]?.roleId&&m.roles.cache.has(state.mutes[m.id].roleId)));
  const cmutes=Object.values(state.overwrites).filter(r=>r.kind==='cmute');
  if(name==='mutelist')return g.list(message,'Mutes en cours',[...muted.map(m=>`<@${m.id}> — ${m.communicationDisabledUntilTimestamp>Date.now()?'timeout jusqu’au '+g.date(m.communicationDisabledUntilTimestamp):'rôle muet'}`),...cmutes.map(r=>`<@${r.targetId}> — salon <#${r.channelId}>`)]);
  return confirm('Retirer tous les mutes du serveur et des salons ?',async()=>{const results=[];for(const m of muted.values())try{engine.assertTarget(message,m);await engine.unmute(m);results.push(`${m.id} : retiré`);}catch(e){results.push(`${m.id} : ${e.message}`);}for(const r of cmutes)try{const c=await guild.channels.fetch(r.channelId);await engine.overwrite(c,r.targetId,'cmute',false);}catch(e){results.push(`${r.targetId} : ${e.message}`);}await g.list(message,'Fin des mutes',results);});
 }
 if(name==='unban'){const ids=await userIds(message,args,client),results=[];for(const id of ids)try{if(settings.blacklisted(id))throw new Error('Retire ce membre de la blacklist avant de le débannir.');await engine.serial(`${guild.id}:user:${id}`,async()=>{await guild.members.unban(id,'Débannissement manuel');store.mutate(guild.id,s=>{delete s.tasks[`ban:${id}`];});store.record(guild.id,id,name,message.author.id,'Débannissement manuel');});results.push(`${id} : débanni`);}catch(e){results.push(`${id} : ${e.message}`);}return g.list(message,'Débannissements',results);}
 if(['addrole','delrole'].includes(name)){
  const groups=args.join(' ').split(',,').map(x=>x.trim()).filter(Boolean);let memberQueries,roleQueries;
  if(groups.length===2){memberQueries=tools.parts([groups[0]]);roleQueries=tools.parts([groups[1]]);}else{const split=args.findIndex(v=>/^<@&\d+>$/.test(v));if(split<1){if(args.length!==2)throw new Error('Utilise membres,,rôles ; groupe les mentions dans chaque partie.');memberQueries=[args[0]];roleQueries=[args[1]];}else{memberQueries=tools.parts(args.slice(0,split));roleQueries=tools.parts(args.slice(split));}}
  const targets=await members(message,memberQueries),roles=[];for(const q of roleQueries)roles.push(await tools.role(message,q));const results=[];
  for(const m of targets)try{engine.assertTarget(message,m);await m.roles[name==='addrole'?'add':'remove'](roles.map(r=>r.id),'Commande de modération');store.record(guild.id,m.id,name,message.author.id,roles.map(r=>r.name).join(', '));results.push(`${m.id} : effectué`);}catch(e){results.push(`${m.id} : ${e.message}`);}return g.list(message,'Rôles',results);
 }
 const timed=['tempmute','tempcmute','tempban'].includes(name),parsed=input(args,timed);
 if(!timed&&args.join(' ').includes(',,')){
  if(['unmute','uncmute','derank'].includes(name)){parsed.queries=tools.parts(args);parsed.reason='Aucune raison';}
  else if(parsed.reason!=='Aucune raison'&&await g.member(message,[parsed.reason])){parsed.queries.push(parsed.reason);parsed.reason='Aucune raison';}
 }
 if(!parsed.queries[0])throw new Error('Membre requis.');
 const targets=await members(message,parsed.queries),results=[];
 for(const member of targets)try{await engine.serial(`${guild.id}:user:${member.id}`,async()=>{
  engine.assertTarget(message,member);const reason=parsed.reason.slice(0,450);
  if(name==='warn'){}else if(['mute','tempmute'].includes(name))await engine.mute(member,parsed.time,reason);
  else if(name==='unmute')await engine.unmute(member);
  else if(['cmute','tempcmute','uncmute'].includes(name)){await engine.overwrite(message.channel,member.id,'cmute',name!=='uncmute');store.mutate(guild.id,s=>{delete s.tasks[`cmute:${message.channel.id}:${member.id}`];if(timed)s.tasks[`cmute:${message.channel.id}:${member.id}`]={kind:'cmute',userId:member.id,channelId:message.channel.id,expiresAt:Date.now()+parsed.time};});}
  else if(name==='kick'){if(!member.kickable)throw new Error('Expulsion impossible.');await member.kick(reason);}
  else if(['ban','tempban'].includes(name)){if(!member.bannable)throw new Error('Ban impossible.');const key=`ban:${member.id}`,previous=store.get(guild.id).tasks[key];store.mutate(guild.id,s=>{delete s.tasks[key];if(timed)s.tasks[key]={kind:'ban',userId:member.id,expiresAt:Date.now()+parsed.time};});try{await member.ban({reason});}catch(error){store.mutate(guild.id,s=>{if(previous)s.tasks[key]=previous;else delete s.tasks[key];});throw error;}}
  else if(name==='derank')await require('./moderation').sanction(member,{action:'derank'},require('./moderationStore').get(guild.id),reason);
  else throw new Error('Commande invalide.');
  store.record(guild.id,member.id,name,message.author.id,reason,parsed.time);
  await require('./logs').send(guild,'mod','Modération manuelle',`**Action :** ${name}\n**Membre :** <@${member.id}>\n**Responsable :** <@${message.author.id}>\n**Raison :** ${reason}`);
 });results.push(`${member.id} : ${name} effectué${name==='mute'&&require('./moderationStore').get(guild.id).timeout?' (timeout Discord de 28 jours)':''}`);}catch(e){results.push(`${member.id} : ${e.message}`);}
 return g.list(message,'Résultat de modération',results);
}
const matches={del:a=>a[0]==='sanction',clear:a=>!a.length||a[0]==='sanctions'||a[0]==='all'&&a[1]==='sanctions'||/^\d+$/.test(a[0])};
module.exports=name=>({name,category:'Modération',defaultPermission:'Administrator',lockedPermission:true,usage:definitions[name],description:descriptions[name],helpEntries:name==='clear'?[{usage:definitions.clear,description:descriptions.clear},{usage:'clear sanctions <membre>',description:'Efface les sanctions d’un membre'},{usage:'clear all sanctions',description:'Efface les sanctions de tous les membres'}]:undefined,matches:matches[name],execute:(m,a,c)=>execute(name,m,a,c)});
module.exports.names=Object.keys(definitions);
module.exports.input=input;
