const { ActionRowBuilder, ButtonBuilder, ButtonStyle, StringSelectMenuBuilder, ChannelType } = require('discord.js');
const { randomUUID } = require('node:crypto');
const fs = require('node:fs'), path = require('node:path');
const g = require('./general'), tools = require('./managementTools'), store = require('./serverConfigStore'), ui = require('./ownerUI');
const interactions = require('./serverConfigInteractions');
const { duration } = require('./antiraidStore');
const definitions = {
perms: ['perms','Affiche les rôles et membres ayant des permissions sur le bot'], slowmode:['slowmode <durée> [salon]','Change le mode lent (maximum 6h)'], autodelete:['autodelete <moderation/snipe> <commande/reply> <on/off/durée>','Configure la suppression automatique des commandes et réponses'], rolemenu:['rolemenu [ID]','Crée ou modifie un menu de rôles'], ticket:['ticket settings','Configure les tickets'], claim:['claim','Prend en charge un ticket'], rename:['rename <nom>','Renomme un ticket'], add:['add <membre>','Ajoute un membre au ticket'], del:['del <membre> / del perm <rôle>','Retire un membre du ticket ou les permissions d’un rôle'], close:['close [raison]','Ferme le ticket après confirmation'], tempvoc:['tempvoc / tempvoc cmd','Configure les vocaux temporaires et affiche leurs commandes'], twitch:['twitch','Configure les alertes de lives Twitch'], join:['join settings','Configure les messages et rôles de bienvenue'], leave:['leave settings','Configure les messages de départ'], reminder:['reminder [nombre] / reminder list','Crée, modifie ou liste les messages programmés'], custom:['custom <mot-clé> / custom transfer <ID/nombre>','Crée une commande personnalisée ou la transfère depuis un serveur'], customlist:['customlist','Affiche les commandes personnalisées'], clear:['clear customs / clear perms','Supprime les commandes personnalisées ou les permissions'], restrict:['restrict <émoji> <rôle>','Réserve un émoji à des rôles'], unrestrict:['unrestrict <émoji>','Rend un émoji accessible à tous'], soutien:['soutien','Configure un rôle lié au statut personnalisé'], set:['set perm <permission/commande> <rôle/membre>','Accorde l’accès à une permission ou commande'], prefix:['prefix <préfixe>','Change le préfixe du serveur'], modmail:['modmail [on/off] [catégorie]','Configure la réception des MP et la création automatique de tickets'], report:['report settings','Configure les signalements par clic droit'], show:['show pics','Configure l’envoi automatique de photos de profil'], autopublish:['autopublish <on/off>','Publie automatiquement les messages des salons d’annonces'], suggestion:['suggestion settings','Configure le salon et le système de suggestions']
};
const on = value => { if (!['on','off'].includes(value)) throw new Error('Indique on ou off.'); return value === 'on'; };
async function execute(name,message,args,client,ownerOnly=false) {
 if (ownerOnly && !require('./settings').isOwner(message.author.id)) throw new Error('Commande réservée aux owners du bot.');
 if (!message.guild) throw new Error('Commande utilisable sur un serveur.');
 const guild=message.guild, config=store.get(guild.id), send=text=>g.reply(message,g.embed('Configuration du serveur',text));
 const form=(title,fields,action)=>ui.form(message,title,fields,action,ownerOnly ? interaction=>require('./settings').isOwner(interaction.user.id) : tools.authorize(message));
 const field=(id,label,value,required=false)=>({id,label,value:value == null ? '' : String(value),required});
 const confirm=(text,action)=>ui.confirm(message,text,action,tools.authorize(message));
 if (['claim','rename','add','close'].includes(name) || name==='del' && args[0]!=='perm') {
  const ticket=config.openTickets[message.channel.id];
  if (!ticket || !interactions.ticketAccess(guild,message.author.id,message.member,ticket,name==='claim')) throw new Error('Ticket introuvable ou accès refusé.');
  if(name==='claim'){ if(ticket.claimedBy && ticket.claimedBy!==message.author.id) throw new Error('Ticket déjà pris en charge.'); store.mutate(guild.id,s=>{s.openTickets[message.channel.id].claimedBy=message.author.id;}); return send('Ticket pris en charge.'); }
  if(name==='rename'){const value=args.join(' '); if(!value || value.length>100) throw new Error('Nom requis, maximum 100 caractères.'); await message.channel.setName(value); return send('Ticket renommé.');}
  if(name==='close') return ui.confirm(message,'Fermer et supprimer ce ticket ?',async()=>{if(!interactions.ticketAccess(guild,message.author.id,await guild.members.fetch(message.author.id),store.get(guild.id).openTickets[message.channel.id])) throw new Error('Accès retiré.'); await interactions.closeTicket(guild,message.channel.id,args.join(' ') || 'Fermeture manuelle');},async i=>interactions.ticketAccess(guild,i.user.id,await guild.members.fetch(i.user.id),store.get(guild.id).openTickets[message.channel.id]));
  const member=await g.member(message,args); if(!member) throw new Error('Membre introuvable.');
  if(name==='del' && [ticket.ownerId,client.user.id].includes(member.id)) throw new Error('Impossible de retirer le créateur ou le bot.');
  if(name==='add') await message.channel.permissionOverwrites.edit(member.id,{ViewChannel:true,SendMessages:true,ReadMessageHistory:true}); else await message.channel.permissionOverwrites.delete(member.id);
  return send('Accès au ticket modifié.');
 }
 if(name==='tempvoc' && args[0]==='cmd') return send('Dans ton vocal temporaire : `tempvoc name <nom>`, `tempvoc limit <0-99>`, `tempvoc lock`, `tempvoc unlock`.');
 if(name==='tempvoc' && ['name','limit','lock','unlock'].includes(args[0])) {
  const channel=message.member.voice.channel, record=config.tempChannels[channel?.id]; if(!record || record.ownerId!==message.author.id) throw new Error('Rejoins le vocal temporaire dont tu es propriétaire.');
  if(args[0]==='name'){const text=args.slice(1).join(' ');if(!text || text.length>100)throw new Error('Nom requis, maximum 100 caractères.');await channel.setName(text);}
  if(args[0]==='limit'){const limit=Number(args[1]);if(!Number.isInteger(limit)||limit<0||limit>99)throw new Error('Limite entre 0 et 99.');await channel.setUserLimit(limit);}
  if(['lock','unlock'].includes(args[0]))await channel.permissionOverwrites.edit(guild.id,{Connect:args[0]==='lock'?false:null});
  return send('Vocal mis à jour.');
 }
 tools.guard(message);
 if(name==='perms')return g.list(message,'Permissions du bot',Object.entries(config.grants).map(([scope,v])=>`**${scope}** : ${v.roles.map(id=>`<@&${id}>`).concat(v.users.map(id=>`<@${id}>`)).join(', ')}`));
 if(name==='slowmode'){const ms=args[0]==='0'?0:duration(args[0]);if(ms>21600000)throw new Error('Maximum 6 heures.');const c=await tools.channel(message,args.slice(1).join(' '));if(!c.setRateLimitPerUser)throw new Error('Salon incompatible.');await c.setRateLimitPerUser(Math.ceil(ms/1000));return send('Mode lent mis à jour.');}
 if(name==='autodelete'){const [group,target,value]=args;if(!['moderation','snipe'].includes(group)||!['commande','reply'].includes(target))throw new Error('Utilise moderation/snipe puis commande/reply.');const ms=value==='off'?null:value==='on'?5000:duration(value);if(ms>3600000)throw new Error('Maximum 1 heure.');store.mutate(guild.id,s=>{s.autodelete[group]||={};s.autodelete[group][target]=ms;});return send('Suppression automatique configurée.');}
 if(name==='prefix'){const value=args.join(' ');if(!value||value.length>16||/\s/.test(value))throw new Error('Préfixe de 1 à 16 caractères sans espace.');const file=path.join(__dirname,'../data/prefixes.json');const data=fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):{};data[guild.id]=value;fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(data,null,2));return send(`Préfixe : \`${value}\``);}
 if(name==='autopublish'){store.mutate(guild.id,s=>{s.autopublish=on(args[0]);});return send('Publication automatique mise à jour.');}
 if(name==='clear'){const key=args[0]==='customs'?'customCommands':args[0]==='perms'?'grants':null;if(!key)throw new Error('Utilise clear customs ou clear perms.');return confirm('Supprimer tous ces réglages ?',()=>store.mutate(guild.id,s=>{s[key]={};}));}
 if(name==='customlist')return g.list(message,'Commandes personnalisées',Object.keys(config.customCommands).map(k=>`\`${k}\``));
 if(name==='custom') {
  const transfer=args[0]==='transfer';let source;
  if(transfer){source=client.guilds.cache.get(args[1])||[...client.guilds.cache.values()][Number(args[1])-1];if(!source || !tools.authorized(source,message.author.id,await source.members.fetch(message.author.id).catch(()=>null)))throw new Error('Accès administrateur requis sur le serveur source.');}
  const keyword=transfer?null:args[0]?.toLowerCase();
  return form(transfer?'Transférer une commande':'Commande personnalisée',transfer?[field('keyword','Mot-clé à transférer','',true)]:[{...field('text','Réponse ({member}, {args}, {server})',config.customCommands[keyword]?.text,true),paragraph:true,max:2000}],async v=>{const key=keyword||v.keyword.toLowerCase();if(!/^[a-z0-9_-]{1,32}$/.test(key)||client.commands.has(key)||client.ownerCommands.has(key)||Object.hasOwn(require('./settings').read().aliases,key))throw new Error('Mot-clé invalide ou réservé.');const text=transfer?store.get(source.id).customCommands[key]?.text:v.text;if(!text)throw new Error('Commande source introuvable.');if(transfer&&Object.hasOwn(config.customCommands,key))throw new Error('Cette commande existe déjà ici.');store.mutate(guild.id,s=>{s.customCommands[key]={text};});});
 }
 if(name==='set'||name==='del'){
  if(args[0]!=='perm')throw new Error('Utilise set perm ou del perm.');
  if(name==='del'){const roles=[];for(const q of args.slice(1).join(' ').split(',,').map(x=>x.trim()).filter(Boolean)){const r=await g.role(message,[q]);if(!r)throw new Error('Rôle introuvable.');roles.push(r.id);}if(!roles.length)throw new Error('Rôle requis.');store.mutate(guild.id,s=>{for(const v of Object.values(s.grants))v.roles=v.roles.filter(id=>!roles.includes(id));});return send('Permissions retirées.');}
  const key=args[1]?.toLowerCase(),command=client.commands.get(key);if(!key||client.ownerCommands.has(key)||command?.lockedPermission)throw new Error('Permission réservée ou commande non délégable.');
  const permission=command?null:require('./permissions').normalize(key);if(permission==='owner')throw new Error('Le grade owner ne peut pas être accordé ici.');
  const recipients=[];for(const query of args.slice(2).join(' ').split(',,').map(x=>x.trim()).filter(Boolean)){const role=await g.role(message,[query]),member=role?null:await g.member(message,[query]);if(!role&&!member)throw new Error('Rôle ou membre introuvable.');recipients.push({type:role?'roles':'users',id:role?.id||member.id});}if(!recipients.length)throw new Error('Rôle ou membre requis.');
  store.mutate(guild.id,s=>{const scope=command?`command:${key}`:`permission:${permission}`;s.grants[scope]||={roles:[],users:[]};for(const recipient of recipients){const list=s.grants[scope][recipient.type];if(!list.includes(recipient.id))list.push(recipient.id);}});return send('Accès accordé.');
 }
 if(['restrict','unrestrict'].includes(name)){const emoji=await guild.emojis.fetch(g.id(args[0]?.match(/\d{15,22}/)?.[0]||args[0]));if(!emoji)throw new Error('Émoji du serveur requis.');const roles=[];if(name==='restrict'){for(const q of args.slice(1).join(' ').split(',,').map(v=>v.trim()).filter(Boolean)){const r=await g.role(message,[q]);if(!r)throw new Error('Rôle introuvable.');roles.push(r.id);}if(!roles.length)throw new Error('Rôle requis.');}await emoji.roles.set(roles);return send('Accès à l’émoji mis à jour.');}
 if(name==='reminder'){if(args[0]==='list')return g.list(message,'Messages programmés',Object.entries(config.reminders).map(([id,r])=>`**${id}** — ${g.date(r.at)} — ${r.sent?'envoyé':'en attente'} — <#${r.channelId}>`));const existing=args[0]?config.reminders[args[0]]:null;if(args[0]&&!existing)throw new Error('Reminder introuvable.');return form('Message programmé',[{...field('text','Message',existing?.text,true),max:2000,paragraph:true},field('date','Date ISO avec fuseau ou durée (ex. 2h)','',true),field('channel','Salon (vide = ici)',existing?.channelId)],async v=>{const at=/^\d{4}-/.test(v.date)?(/(?:Z|[+-]\d{2}:\d{2})$/.test(v.date)?Date.parse(v.date):NaN):Date.now()+duration(v.date);if(!Number.isFinite(at)||at<=Date.now())throw new Error('Date future avec fuseau explicite requise.');const c=await tools.channel(message,v.channel);if(!c.isTextBased())throw new Error('Salon textuel requis.');const id=args[0]||String(Math.max(0,...Object.keys(config.reminders).map(Number))+1);store.mutate(guild.id,s=>{s.reminders[id]={text:v.text,at,channelId:c.id,sent:false};});});}
 if(name==='rolemenu'){const entry=Object.entries(config.roleMenus).find(([id,r])=>id===args[0]||r.messageId===args[0]);if(args[0]&&!entry)throw new Error('Menu introuvable.');return form('Menu de rôles',[field('title','Titre',entry?.[1].title,true),field('roles','Rôles séparés par ,,','',true),field('channel','Salon (vide = ici)',entry?.[1].channelId)],async v=>{const roles=[];for(const q of v.roles.split(',,').map(x=>x.trim()).filter(Boolean)){const r=await tools.role(message,q);if(!interactions.safeRole(r,guild))throw new Error('Les rôles dangereux sont interdits.');if(!roles.some(x=>x.id===r.id))roles.push(r);}if(!roles.length||roles.length>25)throw new Error('Entre 1 et 25 rôles.');const id=entry?.[0]||randomUUID(),c=await tools.channel(message,v.channel);const payload={embeds:[g.embed(v.title,'Choisis tes rôles dans le menu.')],components:[new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(`cfg:roles:${id}`).setMinValues(0).setMaxValues(roles.length).addOptions(roles.map(r=>({label:r.name.slice(0,100),value:r.id}))))]};const sent=entry?await(await c.messages.fetch(entry[1].messageId)).edit(payload):await c.send(payload);store.mutate(guild.id,s=>{s.roleMenus[id]={title:v.title,roleIds:roles.map(r=>r.id),channelId:c.id,messageId:sent.id};});});}
 if(name==='ticket')return form('Paramètres des tickets',[field('enabled','Activer : on/off',config.tickets.enabled?'on':'off',true),field('category','Catégorie (nom ou ID)',config.tickets.categoryId),field('staff','Rôle du support (facultatif)',config.tickets.staffRoleId),field('panel','Salon du bouton de création',config.tickets.panelChannelId),field('logs','Salon de logs (facultatif)',config.tickets.logChannelId)],async v=>{const enabled=on(v.enabled),category=v.category?await tools.channel(message,v.category):null,staff=v.staff?await g.role(message,[v.staff]):null,panel=enabled?await tools.channel(message,v.panel):null,logs=v.logs?await tools.channel(message,v.logs):null;if(category&&category.type!==ChannelType.GuildCategory||v.staff&&!staff)throw new Error('Catégorie ou rôle invalide.');if(panel&&!panel.isTextBased()||logs&&!logs.isTextBased())throw new Error('Salon textuel requis.');if(panel)await panel.send({embeds:[g.embed('Tickets','Ouvre un ticket privé avec le support.')],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('cfg:ticket-open').setLabel('Ouvrir un ticket').setStyle(ButtonStyle.Primary))]});store.mutate(guild.id,s=>{s.tickets={enabled,categoryId:category?.id||null,staffRoleId:staff?.id||null,panelChannelId:panel?.id||null,logChannelId:logs?.id||null};});});
 if(name==='tempvoc')return form('Vocaux temporaires',[field('enabled','Activer : on/off',config.tempVoice.enabled?'on':'off',true),field('hub','Vocal de création',config.tempVoice.hubId,true),field('category','Catégorie',config.tempVoice.categoryId,true)],async v=>{const hub=await tools.channel(message,v.hub,true),category=await tools.channel(message,v.category);if(category.type!==ChannelType.GuildCategory)throw new Error('Catégorie requise.');store.mutate(guild.id,s=>{s.tempVoice={enabled:on(v.enabled),hubId:hub.id,categoryId:category.id};});});
 if(['join','leave'].includes(name)) {const key=name==='join'?'joins':'leaves';return form('Messages de '+(name==='join'?'bienvenue':'départ'),[field('enabled','Activer : on/off',config[key].enabled?'on':'off',true),field('channel','Salon',config[key].channelId),{...field('message','Message : {member}, {user}, {server}',config[key].message,true),paragraph:true,max:2000},...(name==='join'?[field('role','Rôle automatique (facultatif)',config[key].roleId)]:[])],async v=>{const c=await tools.channel(message,v.channel),r=v.role?await tools.role(message,v.role):null;if(!c.isTextBased()||r&&!interactions.safeRole(r,guild))throw new Error('Salon ou rôle incompatible.');store.mutate(guild.id,s=>{s[key]={enabled:on(v.enabled),channelId:c.id,message:v.message,roleId:r?.id||null};});});}
 if(name==='soutien')return form('Rôle de soutien',[field('enabled','Activer : on/off',config.soutien.enabled?'on':'off',true),field('role','Rôle',config.soutien.roleId,true),field('text','Texte dans le statut',config.soutien.text,true)],async v=>{const r=await tools.role(message,v.role);if(!interactions.safeRole(r,guild))throw new Error('Rôle dangereux interdit.');store.mutate(guild.id,s=>{s.soutien={enabled:on(v.enabled),roleId:r.id,text:v.text};});for(const p of guild.presences.cache.values())await require('./serverConfigRuntime').soutien(p);});
 if(name==='twitch')return form('Alertes Twitch',[field('enabled','Activer : on/off',config.twitch.enabled?'on':'off',true),field('channel','Salon',config.twitch.channelId,true),field('users','Identifiants Twitch séparés par ,,',config.twitch.usernames.join(',,'),true)],async v=>{const enabled=on(v.enabled),users=[...new Set(v.users.toLowerCase().split(',,').map(x=>x.trim()).filter(Boolean))];if(!users.length||users.length>100||users.some(x=>!/^\w{1,25}$/.test(x)))throw new Error('Identifiants Twitch invalides (maximum 100).');if(enabled)await require('./twitchAlerts').streams(users);const c=await tools.channel(message,v.channel);if(!c.isTextBased())throw new Error('Salon textuel requis.');store.mutate(guild.id,s=>{s.twitch={enabled,channelId:c.id,usernames:users,liveIds:{}};});});
 if(name==='modmail') {
  const save=async v=>{
   const enabled=on(v.enabled);
   const c=enabled?await tools.channel(message,v.category):null;
   if(enabled&&c.type!==ChannelType.GuildCategory)throw new Error('Catégorie requise.');
   if(enabled){const me=guild.members.me||await guild.members.fetchMe();if(!c.permissionsFor(me)?.has(require('discord.js').PermissionFlagsBits.ManageChannels))throw new Error('Le bot doit pouvoir gérer les salons dans cette catégorie.');}
   store.mutate(guild.id,(s,all)=>{if(enabled&&all.modmailGuildId&&all.modmailGuildId!==guild.id)throw new Error('Le modmail est déjà actif sur un autre serveur.');s.modmail={enabled,categoryId:c?.id||config.modmail.categoryId};all.modmailGuildId=enabled?guild.id:all.modmailGuildId===guild.id?null:all.modmailGuildId;});
  };
  if(['on','off'].includes(args[0])){await save({enabled:args[0],category:args.slice(1).join(' ')||config.modmail.categoryId});return send(args[0]==='on'?'Modmail activé : le premier MP d’un membre crée automatiquement son ticket.':'Modmail désactivé.');}
  return form('Paramètres modmail',[field('enabled','Activer : on/off',config.modmail.enabled?'on':'off',true),field('category','Catégorie',config.modmail.categoryId)],save);
 }
 if(name==='report')return form('Signalements par clic droit',[field('enabled','Activer : on/off',config.report.enabled?'on':'off',true),field('channel','Salon de logs',config.report.logChannelId,true)],async v=>{const enabled=on(v.enabled),c=await tools.channel(message,v.channel);if(!c.isTextBased())throw new Error('Salon textuel requis.');let id=config.report.commandId;if(enabled)id=(await guild.commands.create({name:'Signaler le message',type:3})).id;else if(id)await guild.commands.delete(id).catch(()=>{});store.mutate(guild.id,s=>{s.report={enabled,logChannelId:c.id,commandId:enabled?id:null};});});
 if(name==='show')return form('Photos de profil automatiques',[field('enabled','Activer : on/off',config.showPics.enabled?'on':'off',true),field('channel','Salon',config.showPics.channelId,true),field('interval','Intervalle (minimum 5m)','1h',true)],async v=>{const interval=duration(v.interval);if(interval<300000||interval>31536000000)throw new Error('Intervalle entre 5 minutes et 365 jours.');const c=await tools.channel(message,v.channel);if(!c.isTextBased())throw new Error('Salon textuel requis.');store.mutate(guild.id,s=>{s.showPics={enabled:on(v.enabled),channelId:c.id,interval,nextAt:Date.now()+interval};});});
 if(name==='suggestion')return form('Paramètres des suggestions',[field('enabled','Activer : on/off',config.suggestions.enabled?'on':'off',true),field('channel','Salon',config.suggestions.channelId||g.config.suggestionChannelId,true)],async v=>{const c=await tools.channel(message,v.channel);if(!c.isTextBased())throw new Error('Salon textuel requis.');store.mutate(guild.id,s=>{s.suggestions={enabled:on(v.enabled),channelId:c.id};});});
 throw new Error('Sous-commande invalide.');
}
const matchers={set:a=>a[0]==='perm',clear:a=>['customs','perms'].includes(a[0]),leave:a=>a[0]==='settings',suggestion:a=>a[0]==='settings',show:a=>a[0]==='pics',ticket:a=>a[0]==='settings',join:a=>a[0]==='settings',report:a=>a[0]==='settings'};
const extraEntries={
 del:[['del <membre>','Retire un membre du ticket'],['del perm <rôle>','Retire les permissions du bot à des rôles']],
 tempvoc:[['tempvoc','Configure les vocaux temporaires'],['tempvoc cmd','Affiche les commandes de gestion des vocaux temporaires']],
 reminder:[['reminder [nombre]','Crée ou modifie un message programmé'],['reminder list','Affiche la liste des messages programmés']],
 custom:[['custom <mot-clé>','Crée ou modifie une commande personnalisée'],['custom transfer <ID/nombre>','Transfère une commande personnalisée depuis un autre serveur']],
 clear:[['clear customs','Supprime toutes les commandes personnalisées'],['clear perms','Supprime toutes les permissions du bot']]
};
module.exports=(name,options={})=>({name,category:'Configuration du serveur',defaultPermission:['claim','rename','add','del','close','tempvoc'].includes(name)?'everyone':'Administrator',lockedPermission:!['claim','rename','add','del','close','tempvoc'].includes(name),usage:definitions[name][0],description:definitions[name][1],helpEntries:extraEntries[name]?.map(([usage,description])=>({usage,description})),matches:matchers[name],execute:(m,a,c)=>execute(name,m,a,c,options.ownerOnly)});
module.exports.names=Object.keys(definitions);
